name: Run System Info Script

on: [push, pull_request]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # REMOVE npm install since no dependencies are needed
      - name: Run Node.js Script
        run: node system-info.js
